### ISSUE TITLE
Sort By [Sweet, etc] not working as expected

### ISSUE THREAD

**Issue by LoonyBoB** [Neptunya/infinity-nikki-library#6]
This was working before, but recently it stopped for some reason I'm uncertain of.  When filtering to show Hair and sorting by Sweet, as an example, Blooming Pact comes first, with a Sweet score of 67, ahead of Crystal Poems, with a Sweet score of 535.  Even if I add the Style filter to Sweet, the sixth result - Clear Vision, Sweet score 362 - comes 12 spots ahead of Mellifluous Melody, which has a much better Sweet score of 433.

**Comment by Neptunya** [comment]
Thank you for letting me know of the issue! I accidentally broke sorting by style when adding the recolor toggle to filter options.

**Comment by LoonyBoB** [comment]
Thanks so much for the fast response!  Love your site, it's so helpful :)
