### ISSUE TITLE
Implementing Spreadsheet Resources

### ISSUE THREAD

**Issue by baldwinboy** [Neptunya/infinity-nikki-library#8]
Some resources like the Bouldy Calculator are currently shared as spreadsheets and require that each spreadsheet is duplicated for personalisation. Would you be interested in seeing this implemented on the library so that these resources are more accessible?

**Comment by Neptunya** [comment]
I'm considering features like that in the future, but currently it's not a priority. Thank you for your enthusiasm, but I'm not looking for help on the web development side at this time.
