### ISSUE TITLE
Feathered Dreamscape - Missing secondary label

### ISSUE THREAD

**Issue by Kyle-A-Cooley** [Neptunya/infinity-nikki-library#9]
Feathered Dreamscape is lacking secondary label Fairy. You could probably add some data validation that would prevent other issues when OCR fails. 1 easy option, if its available just use the entire outfit to cross reference the tags. If its not available, use another piece from the set if available to validate.

Hopefully though its something as simple as throwing a try-catch and re-parsing on failure. or if it fails take another screenshot with different dimensions or resolution and re-run ocr. 

Those are some quick thoughts hopefully saving you a bit of time.

**Comment by Neptunya** [comment]
Thank you for letting me know of the issue, I pushed a quick update to my database to fix the missing label. I'll look into adding additional data validation for my OCR, thanks for the suggestions!
